import type { Employee, Doctor, Hospital, Visit, Lead, Camp, MOU, Expense, Notification, User } from "@/types";

export const currentUser: User = { id: "EMP001", name: "Amit Kumar", role: "MARKETING_EXECUTIVE", department: "Corporate Marketing", email: "executive@surya.com" };
export const employees: Employee[] = [
  { id: "EMP001", name: "Amit Kumar", role: "MARKETING_EXECUTIVE", department: "Corporate Marketing", email: "executive@surya.com", designation: "Marketing Executive", phone: "+91 98765 43210", joiningDate: "12 Jan 2023", target: 15, status: "Active", area: "Noida" },
  { id: "EMP002", name: "Neha Sharma", role: "MARKETING_MANAGER", department: "Corporate Marketing", email: "manager@surya.com", designation: "Marketing Manager", phone: "+91 98765 43211", joiningDate: "08 Mar 2021", target: 40, status: "Active", area: "Delhi NCR" },
  { id: "EMP003", name: "Rajiv Mehta", role: "MARKETING_EXECUTIVE", department: "Corporate Marketing", email: "rajiv@surya.com", designation: "Senior Executive", phone: "+91 98765 43212", joiningDate: "15 Jun 2022", target: 18, status: "Active", area: "Ghaziabad" },
  { id: "EMP004", name: "Pooja Verma", role: "MARKETING_EXECUTIVE", department: "Institutional Sales", email: "pooja@surya.com", designation: "Marketing Executive", phone: "+91 98765 43213", joiningDate: "20 Sep 2023", target: 15, status: "Active", area: "Greater Noida" },
  { id: "EMP005", name: "Vikram Singh", role: "MARKETING_EXECUTIVE", department: "Corporate Marketing", email: "vikram@surya.com", designation: "Marketing Executive", phone: "+91 98765 43214", joiningDate: "02 Feb 2024", target: 15, status: "Active", area: "Gurugram" },
];
export const doctors: Doctor[] = ["Ananya Gupta","Siddharth Rao","Meera Iyer","Karan Malhotra","Ritu Bansal","Aarav Joshi","Nisha Kapoor","Rahul Sethi"].map((name, index) => ({ id: `DOC${index + 1}`, name, specialization: ["Cardiology","Orthopedics","Neurology","Gynecology"][index % 4], department: ["Cardiology","Orthopedics","Neurosciences","Women & Child"][index % 4], hospital: ["Surya Hospital Noida","Metro Care Hospital","City Health Centre"][index % 3], location: ["Noida","Delhi","Ghaziabad"][index % 3], phone: `+91 98${index}65 43${index}10`, status: "Active", priority: index % 3 === 0 ? "High" : "Medium" }));
export const hospitals: Hospital[] = ["Surya Hospital Noida","Metro Care Hospital","Kailash Multispeciality","City Health Centre","Fortune Hospital","Green Valley Medical","Apex Care Hospital","Lifeline Hospital"].map((name, index) => ({ id: `HOS${index + 1}`, name, location: ["Noida","Greater Noida","Delhi","Ghaziabad"][index % 4], departments: 8 + index, contact: ["Rakesh Tandon","Priya Nair","Mohit Arora"][index % 3], phone: `+91 120 4${index}5678`, status: "Active", lastVisit: `${index + 1} Aug 2026` }));
export const visits: Visit[] = ["Ananya Gupta","Siddharth Rao","Meera Iyer","Karan Malhotra","Ritu Bansal","Aarav Joshi"].map((doctor, index) => ({ id: `VIS${index + 1}`, doctor, hospital: hospitals[index % hospitals.length].name, executive: index % 2 ? "Neha Sharma" : "Amit Kumar", date: `${19 - index} Aug 2026`, department: doctors[index].department, type: index % 2 ? "Follow-up" : "First Visit", status: index < 4 ? "Completed" : "Scheduled", purpose: "Referral partnership and patient care update" }));
export const leads: Lead[] = ["Kavya Sharma","Rohan Verma","Ishita Singh","Dev Malhotra","Maya Kapoor","Arjun Bhatia","Tara Joshi","Vihaan Mehta"].map((patient, index) => ({ id: `LED${index + 1}`, patient, phone: `+91 97${index}12 45${index}80`, department: doctors[index].department, doctor: doctors[index].name, source: ["Doctor Referral","Camp","Website","Hospital Desk"][index % 4], appointment: `${20 + index} Aug 2026`, executive: index % 2 ? "Neha Sharma" : "Amit Kumar", status: ["New","Contacted","Appointment Scheduled","OPD Converted","IPD Converted"][index % 5] as Lead["status"], revenue: index % 5 > 2 ? 12500 + index * 1800 : 0 }));
export const camps: Camp[] = [{ id: "CAM001", name: "Heart Health Screening", location: "Sector 62, Noida", date: "24 Aug 2026", registrations: 120, leads: 46, opd: 18, ipd: 4, revenue: 85600, status: "Upcoming" }, { id: "CAM002", name: "Women Wellness Drive", location: "Jewar Community Hall", date: "15 Aug 2026", registrations: 86, leads: 31, opd: 12, ipd: 3, revenue: 49200, status: "Completed" }, { id: "CAM003", name: "Diabetes Awareness Camp", location: "Gurugram", date: "30 Aug 2026", registrations: 94, leads: 28, opd: 0, ipd: 0, revenue: 0, status: "Upcoming" }];
export const mous: MOU[] = [{ id: "MOU001", organization: "TechNova Industries", contact: "Sanjay Menon", agreementDate: "12 Feb 2025", expiryDate: "06 Sep 2026", status: "Expiring Soon" }, { id: "MOU002", organization: "Noida Wellness Network", contact: "Asha Verma", agreementDate: "20 Apr 2024", expiryDate: "18 Mar 2027", status: "Active" }, { id: "MOU003", organization: "Greater Noida School Board", contact: "Ravi Gupta", agreementDate: "02 Jan 2023", expiryDate: "28 Jul 2026", status: "Expired" }];
export const expenses: Expense[] = ["Fuel reimbursement - Noida visits","Partner lunch meeting","Printing camp brochures","Parking - Sector 62","Auto fare - Delhi visit"].map((description, index) => ({ id: `EXP${index + 1}`, date: `${18 - index} Aug 2026`, employee: index % 2 ? "Neha Sharma" : "Amit Kumar", category: ["Fuel","Food","Printing","Parking","Miscellaneous"][index], description, amount: [1240, 1850, 3200, 180, 650][index], status: index === 1 ? "Approved" : "Pending" }));
export const notifications: Notification[] = [{ id: "N1", title: "Follow-up due today", description: "Call Dr. Siddharth Rao at Metro Care Hospital.", time: "10 min ago", type: "follow-up", read: false }, { id: "N2", title: "Camp reminder", description: "Heart Health Screening is scheduled in 5 days.", time: "1 hr ago", type: "camp", read: false }, { id: "N3", title: "Daily target reminder", description: "You are 5 visits away from today's target.", time: "3 hrs ago", type: "target", read: true }];
