"use client";

import { Activity, Bell, CalendarCheck, FileText, Target, Users } from "lucide-react";
import { CollectionPage, type CollectionField, type CollectionColumn } from "@/components/collection-page";
import { CampModeControl } from "@/components/camp-mode-control";
import { PageHeader, StatCard } from "@/components/ui";

const hospitalFields: CollectionField[] = [{ name: "name", label: "Hospital name", required: true }, { name: "address", label: "Address", required: true }, { name: "latitude", label: "Latitude", type: "number" }, { name: "longitude", label: "Longitude", type: "number" }, { name: "departments", label: "Departments", type: "number" }, { name: "contactPerson", label: "Contact person" }, { name: "phone", label: "Phone", type: "tel" }, { name: "email", label: "Email", type: "email" }, { name: "notes", label: "Notes", type: "textarea" }, { name: "status", label: "Status", type: "select", options: ["ACTIVE", "INACTIVE"] }];
const hospitalColumns: CollectionColumn[] = [{ name: "name", label: "Hospital" }, { name: "address", label: "Address" }, { name: "departments", label: "Departments" }, { name: "contactPerson", label: "Contact" }, { name: "phone", label: "Phone" }, { name: "status", label: "Status" }];
const doctorFields: CollectionField[] = [{ name: "name", label: "Doctor name", required: true }, { name: "hospital", label: "Hospital", required: true }, { name: "department", label: "Department", required: true }, { name: "specialty", label: "Specialty", required: true }, { name: "phone", label: "Phone", type: "tel" }, { name: "email", label: "Email", type: "email" }, { name: "notes", label: "Notes", type: "textarea" }, { name: "status", label: "Status", type: "select", options: ["ACTIVE", "INACTIVE"] }];
const doctorColumns: CollectionColumn[] = [{ name: "name", label: "Doctor" }, { name: "specialty", label: "Specialty" }, { name: "hospital", label: "Hospital" }, { name: "department", label: "Department" }, { name: "phone", label: "Phone" }, { name: "status", label: "Status" }];
const visitFields: CollectionField[] = [{ name: "date", label: "Visit date", type: "date", required: true }, { name: "doctor", label: "Doctor", required: true }, { name: "hospital", label: "Hospital", required: true }, { name: "visitType", label: "Visit type", type: "select", options: ["FIRST_VISIT", "FOLLOW_UP", "CAMP_VISIT"] }, { name: "purpose", label: "Purpose", required: true }, { name: "notes", label: "Notes", type: "textarea" }, { name: "outcome", label: "Outcome", type: "textarea" }, { name: "status", label: "Status", type: "select", options: ["PLANNED", "COMPLETED", "CANCELLED"] }];
const visitColumns: CollectionColumn[] = [{ name: "doctor", label: "Doctor" }, { name: "hospital", label: "Hospital" }, { name: "date", label: "Date" }, { name: "purpose", label: "Purpose" }, { name: "status", label: "Status" }];
const leadFields: CollectionField[] = [{ name: "patient", label: "Patient/lead name", required: true }, { name: "phone", label: "Phone", type: "tel", required: true }, { name: "hospital", label: "Hospital", required: true }, { name: "source", label: "Lead source", type: "select", options: ["Doctor Referral", "Camp", "Hospital Visit", "Digital", "WhatsApp", "Phone", "Walk-in", "Other"] }, { name: "opdIpd", label: "OPD/IPD", type: "select", options: ["OPD", "IPD"] }, { name: "status", label: "Lead status", type: "select", options: ["NEW", "CONTACTED", "FOLLOW_UP", "APPOINTMENT", "OPD_CONVERTED", "IPD_CONVERTED", "LOST"] }, { name: "revenue", label: "Revenue", type: "number" }, { name: "notes", label: "Notes", type: "textarea" }];
const leadColumns: CollectionColumn[] = [{ name: "patient", label: "Patient" }, { name: "department", label: "Department" }, { name: "doctor", label: "Doctor" }, { name: "source", label: "Source" }, { name: "status", label: "Status" }, { name: "revenue", label: "Revenue", currency: true }];
const campFields: CollectionField[] = [{ name: "name", label: "Camp name", required: true }, { name: "location", label: "Location", required: true }, { name: "date", label: "Date", type: "date", required: true }, { name: "organizer", label: "Organizer" }, { name: "registrations", label: "Registrations", type: "number" }, { name: "leads", label: "Leads", type: "number" }, { name: "opd", label: "OPD", type: "number" }, { name: "ipd", label: "IPD", type: "number" }, { name: "revenue", label: "Revenue", type: "number" }, { name: "expenses", label: "Expenses", type: "number" }, { name: "notes", label: "Notes", type: "textarea" }, { name: "status", label: "Status", type: "select", options: ["PLANNED", "COMPLETED", "CANCELLED"] }];
const campColumns: CollectionColumn[] = [{ name: "name", label: "Camp" }, { name: "location", label: "Location" }, { name: "date", label: "Date" }, { name: "registrations", label: "Registrations" }, { name: "leads", label: "Leads" }, { name: "status", label: "Status" }];
const expenseFields: CollectionField[] = [{ name: "date", label: "Date", type: "date", required: true }, { name: "category", label: "Category", type: "select", options: ["Fuel", "Parking", "Food", "Hotel", "Printing", "Miscellaneous"] }, { name: "amount", label: "Amount", type: "number", required: true }, { name: "description", label: "Description", required: true }, { name: "status", label: "Approval status", type: "select", options: ["PENDING", "APPROVED", "REJECTED"] }];
const expenseColumns: CollectionColumn[] = [{ name: "date", label: "Date" }, { name: "category", label: "Category" }, { name: "description", label: "Description" }, { name: "amount", label: "Amount", currency: true }, { name: "status", label: "Status" }];
const mouFields: CollectionField[] = [{ name: "organization", label: "Organization", required: true }, { name: "contactPerson", label: "Contact person", required: true }, { name: "phone", label: "Phone", type: "tel" }, { name: "email", label: "Email", type: "email" }, { name: "agreementDate", label: "Agreement date", type: "date" }, { name: "expiryDate", label: "Expiry date", type: "date", required: true }, { name: "status", label: "Status", type: "select", options: ["ACTIVE", "EXPIRING_SOON", "EXPIRED", "RENEWED"] }, { name: "notes", label: "Notes", type: "textarea" }];
const mouColumns: CollectionColumn[] = [{ name: "organization", label: "Organization" }, { name: "contactPerson", label: "Contact" }, { name: "agreementDate", label: "Agreement date" }, { name: "expiryDate", label: "Expiry date" }, { name: "status", label: "Status" }];
const employeeFields: CollectionField[] = [{ name: "employeeId", label: "Employee ID", required: true }, { name: "name", label: "Name", required: true }, { name: "email", label: "Email", type: "email", required: true }, { name: "phone", label: "Phone", type: "tel" }, { name: "department", label: "Department", required: true }, { name: "designation", label: "Designation" }, { name: "joiningDate", label: "Joining date", type: "date" }, { name: "role", label: "Role", type: "select", options: ["MARKETING_EXECUTIVE", "MARKETING_MANAGER", "SUPER_ADMIN"] }, { name: "status", label: "Status", type: "select", options: ["ACTIVE", "INACTIVE", "SUSPENDED"] }];
const employeeColumns: CollectionColumn[] = [{ name: "name", label: "Employee" }, { name: "email", label: "Email" }, { name: "department", label: "Department" }, { name: "designation", label: "Designation" }, { name: "role", label: "Role" }, { name: "status", label: "Status" }];

export function VisitsPage() { return <CollectionPage title="Doctor visits" description="Plan, track and review field touchpoints across your network." collection="doctorVisits" actionLabel="Add visit" fields={visitFields} columns={visitColumns} statusField="status" />; }
export function DoctorsPage() { return <CollectionPage title="Doctors" description="Your relationship directory for referral partners and specialists." collection="doctors" actionLabel="Add doctor" fields={doctorFields} columns={doctorColumns} statusField="status" />; }
export function HospitalsPage() { return <CollectionPage title="Hospitals" description="Manage partner facilities, contacts and visit history." collection="hospitals" actionLabel="Add hospital" fields={hospitalFields} columns={hospitalColumns} statusField="status" />; }
export function LeadsPage() { return <CollectionPage title="Leads" description="Track every referral from first contact through conversion." collection="leads" actionLabel="Add lead" fields={leadFields} columns={leadColumns} statusField="status" />; }
export function EmployeesPage() { return <CollectionPage title="Employees" description="Manage field teams, targets and access across the region." collection="users" actionLabel="Add employee" fields={employeeFields} columns={employeeColumns} statusField="status" />; }
export function CampsPage() { return <><CampModeControl /><CollectionPage title="Health camps" description="Coordinate outreach camps and measure community impact." collection="camps" actionLabel="Add camp" fields={campFields} columns={campColumns} statusField="status" /></>; }
export function MouPage() { return <CollectionPage title="MOU tracker" description="Keep institutional partnerships current and renewal-ready." collection="mou" actionLabel="Add MOU" fields={mouFields} columns={mouColumns} statusField="status" />; }
export function ExpensesPage() { return <CollectionPage title="Expenses" description="Review reimbursements and keep field spend accountable." collection="expenses" actionLabel="Add expense" fields={expenseFields} columns={expenseColumns} statusField="status" />; }
export function ReportsPage() { return <GenericPage title="Reports" description="Reports now use the live Firestore modules and are ready for export integration." />; }
export function NotificationsPage() { return <CollectionPage title="Notifications" description="Stay ahead of follow-ups, camps and approvals." collection="notifications" actionLabel="Add notification" fields={[{ name: "title", label: "Title", required: true }, { name: "description", label: "Description", type: "textarea", required: true }, { name: "type", label: "Category", type: "select", options: ["FOLLOW_UP", "ATTENDANCE", "CAMP", "MOU", "TARGET", "EXPENSE"] }, { name: "read", label: "State", type: "select", options: ["false", "true"] }]} columns={[{ name: "title", label: "Title" }, { name: "description", label: "Description" }, { name: "type", label: "Category" }, { name: "read", label: "Read" }]} />; }
export function ScorecardPage() { return <GenericPage title="Employee scorecard" description="Performance metrics are calculated from Firestore activity records." />; }
export function GenericPage({ title, description }: { title: string; description: string }) { return <><PageHeader eyebrow="Workspace" title={title} description={description} /><div className="grid gap-5 md:grid-cols-3"><StatCard label="This month" value="Live" detail="Firestore connected" icon={Target} /><StatCard label="Open items" value="Review" detail="Use the module list" icon={Activity} tone="teal" /><StatCard label="Completion" value="Ready" detail="Data-driven workflows" icon={CalendarCheck} tone="amber" /></div></>; }
