"use client";

import { useParams } from "next/navigation";
import { CollectionPage } from "@/components/collection-page";
import { PageHeader } from "@/components/ui";

const configs: Record<string, { title: string; collection: string; columns: { name: string; label: string; currency?: boolean }[]; fields: { name: string; label: string; type?: "text" | "email" | "tel" | "date" | "number" | "textarea" | "select"; required?: boolean; options?: string[] }[] }> = {
  employees: { title: "Employees", collection: "users", columns: [{ name: "name", label: "Employee" }, { name: "email", label: "Email" }, { name: "department", label: "Department" }, { name: "role", label: "Role" }, { name: "gpsPolicy", label: "GPS policy" }, { name: "status", label: "Status" }], fields: [{ name: "employeeId", label: "Employee ID", required: true }, { name: "name", label: "Name", required: true }, { name: "email", label: "Official email", type: "email", required: true }, { name: "department", label: "Department", type: "select", options: ["MARKETING", "HR", "FINANCE", "ACCOUNTS", "OPERATIONS", "OTHER"] }, { name: "role", label: "Role", type: "select", options: ["ADMIN", "MARKETING_MANAGER", "MARKETING_EXECUTIVE", "EMPLOYEE"] }, { name: "gpsPolicy", label: "GPS policy", type: "select", options: ["MANDATORY", "OPTIONAL", "DISABLED"] }, { name: "campAccess", label: "Camp access", type: "select", options: ["true", "false"] }, { name: "status", label: "Status", type: "select", options: ["ACTIVE", "INACTIVE", "SUSPENDED"] }] },
  hospitals: { title: "Hospitals", collection: "hospitals", columns: [{ name: "name", label: "Hospital" }, { name: "address", label: "Address" }, { name: "phone", label: "Phone" }, { name: "status", label: "Status" }], fields: [{ name: "name", label: "Hospital name", required: true }, { name: "address", label: "Address", required: true }, { name: "phone", label: "Phone", type: "tel" }, { name: "status", label: "Status", type: "select", options: ["ACTIVE", "INACTIVE"] }] },
  doctors: { title: "Doctors", collection: "doctors", columns: [{ name: "name", label: "Doctor" }, { name: "specialty", label: "Specialty" }, { name: "hospital", label: "Hospital" }, { name: "status", label: "Status" }], fields: [{ name: "name", label: "Doctor name", required: true }, { name: "specialty", label: "Specialty", required: true }, { name: "hospital", label: "Hospital", required: true }, { name: "status", label: "Status", type: "select", options: ["ACTIVE", "INACTIVE"] }] },
  leads: { title: "Leads", collection: "leads", columns: [{ name: "patient", label: "Patient" }, { name: "department", label: "Department" }, { name: "status", label: "Status" }, { name: "revenue", label: "Revenue", currency: true }], fields: [{ name: "patient", label: "Patient name", required: true }, { name: "department", label: "Department", required: true }, { name: "status", label: "Status", type: "select", options: ["NEW", "CONTACTED", "FOLLOW_UP", "APPOINTMENT", "OPD_CONVERTED", "IPD_CONVERTED", "LOST"] }, { name: "revenue", label: "Revenue", type: "number" }] },
  camps: { title: "Camps", collection: "camps", columns: [{ name: "name", label: "Camp" }, { name: "location", label: "Location" }, { name: "date", label: "Date" }, { name: "status", label: "Status" }], fields: [{ name: "name", label: "Camp name", required: true }, { name: "location", label: "Location", required: true }, { name: "date", label: "Date", type: "date", required: true }, { name: "status", label: "Status", type: "select", options: ["PLANNED", "COMPLETED", "CANCELLED"] }] },
  expenses: { title: "Expenses", collection: "expenses", columns: [{ name: "date", label: "Date" }, { name: "category", label: "Category" }, { name: "amount", label: "Amount", currency: true }, { name: "status", label: "Status" }], fields: [{ name: "date", label: "Date", type: "date", required: true }, { name: "category", label: "Category", type: "select", options: ["Fuel", "Parking", "Food", "Hotel", "Printing", "Miscellaneous"] }, { name: "amount", label: "Amount", type: "number", required: true }, { name: "status", label: "Status", type: "select", options: ["PENDING", "APPROVED", "REJECTED"] }] },
};

export default function AdminModulePage() { const params = useParams<{ slug: string[] }>(); const key = params.slug?.join("/") ?? ""; const config = configs[key]; if (!config) return <><PageHeader eyebrow="Administration" title={key.replaceAll("-", " ")} description="This administrative workspace is reserved for authorized operational records." /><div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">No records are configured for this view yet.</div></>; return <CollectionPage title={config.title} description={`Organization-wide ${config.title.toLowerCase()} management.`} collection={config.collection} actionLabel={`Add ${config.title.slice(0, -1).toLowerCase()}`} fields={config.fields} columns={config.columns} statusField="status" />; }
