"use client";
import Link from "next/link";
import { Plus, Search, ArrowUpRight, Download } from "lucide-react";
import { Badge, Button, PageHeader, Avatar, EmptyState } from "@/components/ui";
import { formatCurrency } from "@/lib/utils";
import type { Doctor, Hospital, Visit, Lead, Camp, MOU, Expense, Employee } from "@/types";
export function ModulePage({ title, description, actionLabel = "Add new", href = "#", children }: { title: string; description: string; actionLabel?: string; href?: string; children: React.ReactNode }) { return <><PageHeader eyebrow="Operations" title={title} description={description} action={<div className="flex gap-2"><Button variant="secondary"><Download size={16}/>Export</Button><Link href={href}><Button><Plus size={16}/>{actionLabel}</Button></Link></div>} />{children}</>; }
export function TableToolbar({ placeholder = "Search records..." }: { placeholder?: string }) { return <div className="mb-4 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input placeholder={placeholder} className="h-10 w-full rounded-xl border border-slate-200 bg-white pl-10 text-sm outline-none focus:border-blue-400"/></div><select className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-600"><option>All statuses</option><option>Active</option><option>Pending</option></select></div>; }
function Table({ headers, rows }: { headers: string[]; rows: React.ReactNode[][] }) { return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-slate-100 bg-slate-50 text-[11px] font-extrabold uppercase tracking-wider text-slate-500"><tr>{headers.map((header) => <th key={header} className="px-5 py-4">{header}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row,index) => <tr key={index} className="transition hover:bg-blue-50/30">{row.map((cell,cellIndex) => <td key={cellIndex} className="px-5 py-4">{cell}</td>)}</tr>)}</tbody></table></div></div>; }
const tone = (value: string) => value === "Active" || value === "Completed" || value === "Approved" || value === "OPD Converted" || value === "Upcoming" ? "green" : value === "Expired" || value === "Rejected" || value === "Lost" ? "red" : "amber";
export function DoctorsTable({ data }: { data: Doctor[] }) { return <><TableToolbar placeholder="Search doctors, specializations..."/><Table headers={["Doctor","Specialization","Hospital","Location","Priority","Status","Action"]} rows={data.map((doctor) => [<span className="flex items-center gap-3 font-bold"><Avatar name={doctor.name} size="sm"/>{doctor.name}</span>, doctor.specialization, doctor.hospital, doctor.location, <Badge tone={doctor.priority === "High" ? "red" : "amber"}>{doctor.priority}</Badge>, <Badge tone={tone(doctor.status)}>{doctor.status}</Badge>, <Link href={`/doctors/${doctor.id}`} className="text-blue-600"><ArrowUpRight size={17}/></Link>])}/></>; }
export function HospitalsTable({ data }: { data: Hospital[] }) { return <><TableToolbar placeholder="Search hospitals..."/><Table headers={["Hospital","Location","Departments","Contact","Last visit","Status","Action"]} rows={data.map((hospital) => [<span className="font-bold">{hospital.name}</span>, hospital.location, hospital.departments, hospital.contact, hospital.lastVisit, <Badge tone={tone(hospital.status)}>{hospital.status}</Badge>, <Link href={`/hospitals/${hospital.id}`} className="text-blue-600"><ArrowUpRight size={17}/></Link>])}/></>; }
export function VisitsTable({ data }: { data: Visit[] }) { return <><TableToolbar placeholder="Search visits, doctors..."/><Table headers={["Doctor","Hospital","Executive","Date","Type","Status","Action"]} rows={data.map((visit) => [<span className="font-bold">{visit.doctor}</span>, visit.hospital, visit.executive, visit.date, visit.type, <Badge tone={tone(visit.status)}>{visit.status}</Badge>, <Link href={`/visits/${visit.id}`} className="text-blue-600"><ArrowUpRight size={17}/></Link>])}/></>; }
export function LeadsTable({ data }: { data: Lead[] }) { return <><TableToolbar placeholder="Search leads, patients..."/><Table headers={["Patient","Department","Doctor","Source","Appointment","Status","Revenue"]} rows={data.map((lead) => [<span className="font-bold">{lead.patient}</span>, lead.department, lead.doctor, lead.source, lead.appointment, <Badge tone={tone(lead.status)}>{lead.status}</Badge>, formatCurrency(lead.revenue)])}/></>; }
export function EmployeesTable({ data }: { data: Employee[] }) { return <><TableToolbar placeholder="Search employees..."/><Table headers={["Employee","Department","Designation","Area","Target","Status","Action"]} rows={data.map((employee) => [<span className="flex items-center gap-3 font-bold"><Avatar name={employee.name} size="sm"/>{employee.name}</span>, employee.department, employee.designation, employee.area, `${employee.target} visits`, <Badge tone={tone(employee.status)}>{employee.status}</Badge>, <Link href={`/employees/${employee.id}`} className="text-blue-600"><ArrowUpRight size={17}/></Link>])}/></>; }
export function CampsTable({ data }: { data: Camp[] }) { return <><TableToolbar placeholder="Search camps..."/><Table headers={["Camp","Location","Date","Registrations","Leads","OPD","IPD","Status"]} rows={data.map((camp) => [<span className="font-bold">{camp.name}</span>, camp.location, camp.date, camp.registrations, camp.leads, camp.opd, camp.ipd, <Badge tone={tone(camp.status)}>{camp.status}</Badge>])}/></>; }
export function MouTable({ data }: { data: MOU[] }) { return <><TableToolbar placeholder="Search organizations..."/><Table headers={["Organization","Contact","Agreement date","Expiry date","Status","Action"]} rows={data.map((mou) => [<span className="font-bold">{mou.organization}</span>, mou.contact, mou.agreementDate, mou.expiryDate, <Badge tone={tone(mou.status)}>{mou.status}</Badge>, <Link href={`/mou/${mou.id}`} className="text-blue-600"><ArrowUpRight size={17}/></Link>])}/></>; }
export function ExpensesTable({ data }: { data: Expense[] }) { return <><TableToolbar placeholder="Search expenses..."/><Table headers={["Date","Employee","Category","Description","Amount","Status"]} rows={data.map((expense) => [expense.date, expense.employee, expense.category, expense.description, formatCurrency(expense.amount), <Badge tone={tone(expense.status)}>{expense.status}</Badge>])}/></>; }
