"use client";
import { motion } from "framer-motion";
import { ArrowUpRight, ChevronDown, Search, SlidersHorizontal } from "lucide-react";
import { cn } from "@/lib/utils";
export function Badge({ children, tone = "blue" }: { children: React.ReactNode; tone?: "blue" | "green" | "amber" | "red" | "gray" }) { const styles = { blue: "bg-blue-50 text-blue-700", green: "bg-emerald-50 text-emerald-700", amber: "bg-amber-50 text-amber-700", red: "bg-rose-50 text-rose-700", gray: "bg-slate-100 text-slate-600" }; return <span className={cn("inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-bold", styles[tone])}>{children}</span>; }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-[0.2em] text-teal-600">{eyebrow || "Workspace"}</p><h1 className="text-2xl font-extrabold text-[#102a43] sm:text-3xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm text-slate-500">{description}</p>}</div>{action}</div>; }
export function Button({ children, variant = "primary", className, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger" }) { const variants = { primary: "bg-[#1473e6] text-white shadow-blue-200 hover:bg-[#0e5fc4]", secondary: "border border-slate-200 bg-white text-[#102a43] hover:bg-slate-50", ghost: "text-slate-500 hover:bg-slate-100", danger: "bg-rose-600 text-white hover:bg-rose-700" }; return <button className={cn("inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-4 text-sm font-bold transition active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-50", variants[variant], className)} {...props}>{children}</button>; }
export function StatCard({ label, value, detail, icon: Icon, tone = "blue" }: { label: string; value: string; detail: string; icon: React.ElementType; tone?: "blue" | "teal" | "amber" | "purple" }) { const colors = { blue: "bg-blue-50 text-blue-600", teal: "bg-teal-50 text-teal-600", amber: "bg-amber-50 text-amber-600", purple: "bg-violet-50 text-violet-600" }; return <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_24px_rgba(16,42,67,.04)]"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-extrabold text-[#102a43]">{value}</p></div><div className={cn("rounded-xl p-2.5", colors[tone])}><Icon size={18} /></div></div><p className="mt-4 flex items-center gap-1 text-xs font-semibold text-emerald-600"><ArrowUpRight size={14} />{detail}</p></motion.div>; }
export function ProgressBar({ value, color = "bg-blue-600" }: { value: number; color?: string }) { return <div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={cn("h-full rounded-full transition-all", color)} style={{ width: `${Math.min(value, 100)}%` }} /></div>; }
export function SearchBox({ placeholder = "Search workspace..." }: { placeholder?: string }) { return <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} /><input aria-label={placeholder} placeholder={placeholder} className="h-10 w-full rounded-xl border border-slate-200 bg-white pl-10 pr-3 text-sm outline-none transition focus:border-blue-400 focus:ring-4 focus:ring-blue-50" /></div>; }
export function SelectBox({ label, options }: { label: string; options: string[] }) { return <label className="block text-xs font-bold text-slate-500">{label}<div className="relative mt-1.5"><select className="h-10 w-full appearance-none rounded-xl border border-slate-200 bg-white px-3 pr-8 text-sm font-medium text-slate-700 outline-none focus:border-blue-400">{options.map((option) => <option key={option}>{option}</option>)}</select><ChevronDown size={15} className="pointer-events-none absolute right-3 top-3 text-slate-400" /></div></label>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><div className="mx-auto mb-3 flex h-11 w-11 items-center justify-center rounded-full bg-slate-100"><SlidersHorizontal size={18} className="text-slate-400" /></div><h3 className="font-bold text-[#102a43]">{title}</h3><p className="mt-1 text-sm text-slate-500">{description}</p></div>; }
export function Avatar({ name, photoURL, size = "md" }: { name: string; photoURL?: string; size?: "sm" | "md" }) { return <div className={cn("flex shrink-0 items-center justify-center overflow-hidden rounded-full bg-[#d8f1ee] font-bold text-teal-700", size === "sm" ? "h-7 w-7 text-[10px]" : "h-9 w-9 text-xs")} aria-label={name}>{photoURL ? <img src={photoURL} alt="" className="h-full w-full object-cover" /> : name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</div>; }
