"use client";
import Link from "next/link";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowLeft, CheckCircle2 } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { BrandLogo } from "@/components/brand-logo";
import { Button } from "@/components/ui";
import { submitEmployeeRequest } from "@/lib/firebase/requests";
import { toast } from "sonner";
const schema = z.object({ employeeId: z.string().min(2), name: z.string().min(2), email: z.string().email(), phone: z.string().min(10), department: z.string().min(2), designation: z.string().min(2), joiningDate: z.string().min(1), managerId: z.string().min(1) });
type Values = z.infer<typeof schema>;
export default function RegisterPage() { const [submitted, setSubmitted] = useState(false); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(schema) }); const submit = async (values: Values) => { try { await submitEmployeeRequest(values); setSubmitted(true); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to submit request."); } }; if (submitted) return <main className="flex min-h-screen items-center justify-center bg-[#f4f8fb] p-6"><div className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-xl"><CheckCircle2 className="mx-auto text-teal-600" size={42} /><h1 className="mt-4 text-2xl font-extrabold text-[#102a43]">Your registration request has been submitted.</h1><p className="mt-3 text-sm text-slate-500">Your account will be activated after Admin approval.</p><Link href="/login" className="mt-6 inline-block font-bold text-blue-600">Return to Employee Login</Link></div></main>; return <main className="min-h-screen bg-[#f4f8fb] p-6 sm:p-10"><div className="mx-auto max-w-3xl"><Link href="/login" className="inline-flex items-center gap-2 text-sm font-bold text-blue-600"><ArrowLeft size={16} />Back to Employee Login</Link><div className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-xl sm:p-9"><BrandLogo className="h-16 w-16 rounded-xl bg-white p-1" /><h1 className="mt-5 text-3xl font-extrabold text-[#102a43]">Request Employee Access</h1><p className="mt-2 text-sm text-slate-500">Employee access requires administrator approval.</p><div className="mt-5 grid gap-2 rounded-xl bg-blue-50 p-4 text-sm text-blue-800"><span>1. Submit your employee details.</span><span>2. Admin verifies your request.</span><span>3. Your account is activated.</span><span>4. Login using your registered official email.</span></div><form onSubmit={handleSubmit(submit)} className="mt-7 grid gap-4 sm:grid-cols-2">{[{ name: "employeeId", label: "Employee ID" }, { name: "name", label: "Full Name" }, { name: "email", label: "Official Email", type: "email" }, { name: "phone", label: "Phone Number" }, { name: "department", label: "Department" }, { name: "designation", label: "Designation" }, { name: "joiningDate", label: "Joining Date", type: "date" }, { name: "managerId", label: "Reporting Manager" }].map((field) => <label key={field.name} className="text-sm font-bold text-[#102a43]">{field.label}<input {...register(field.name as keyof Values)} type={field.type ?? "text"} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm font-normal outline-none focus:border-blue-400" />{errors[field.name as keyof Values] && <span className="mt-1 block text-xs text-rose-600">This field is required.</span>}</label>)}<div className="sm:col-span-2"><Button disabled={isSubmitting}>{isSubmitting ? "Submitting..." : "Submit Access Request"}</Button></div></form></div></div></main>; }
